package info.fmro.shared.stream.enums;

public enum ErrorCode {
    NO_APP_KEY,
    INVALID_APP_KEY,
    NO_SESSION,
    INVALID_SESSION_INFORMATION,
    NOT_AUTHORIZED,
    INVALID_INPUT,
    INVALID_CLOCK,
    UNEXPECTED_ERROR,
    TIMEOUT,
    SUBSCRIPTION_LIMIT_EXCEEDED,
    INVALID_REQUEST,
    CONNECTION_FAILED,
    MAX_CONNECTION_LIMIT_EXCEEDED
}
